### ISSUE TITLE
How do I dump the error_log traceback to the browser?

### ISSUE THREAD

**Issue by jfoclpf** [zopefoundation/Products.SiteErrorLog#29]
It's not exactly a bug report, but to ease the error log view traceback for developers?

We are a big org here (~6000 people) and we use Python Zope. We have naturally two versions: prod and dev. In production I understand due to security reasons we should not show error log to end users, but how do I do that for dev or for admin accounts? It is very cumbersome to check the error log manually every time I get an internal server error.

Can I dump the error log traceback directly onto the browser? 

Zope v. 4.6.2
Python v. 3.8.0b2 (default, Jul 9 2019, 16:47:40) [GCC 4.8.5]

**Comment by dataflake** [comment]
There's no method to dump the entire log into the browser outside of the list on the ZMI page `manage_main` of the error log object. You can view specific entries as text or HTML if you know the internal ID of the error. The text representation uses the `getLogEntryAsText` method, so if your error log object is at the root of the site and has an id `error_log` you could visit the path `/error_log/getLogEntryAsText?id=1646926247.56298110.032533870052725566` (and provide an actual ID). The method `showEntry` also requires a err or ID and provides an HTML view: `/showEntry?id=1646926247.56298110.032533870052725566`.

**Comment by dataflake** [comment]
P.S.: Check https://community.plone.org/t/plone-5-2-wsgi-maillogger-alternative/7961/4 for a solution that sends logging messages by email by defining an SMTP handler inside the WSGI configuration file and using that handler for anything that also flows to the filesystem event log. It's important that the SMTP server receiving the log messages is fast and does not block, otherwise your site performance will suffer any time an error is logged.

**Comment by jfoclpf** [comment]
Thank you @dataflake for you reply

Maybe I was not clear enough: I don't want to dump the whole log file onto the browser, I just want the  traceback error which is in log file, triggered by the corresponding HTTP request.

For example, when I make a HTTP request on the browser, instead of getting from the browser "Internal server error", I want to have on the browser the traceback error caused by such HTTP request. 

That would help debugging, because I don't need to go to the error_log every time I get an internal server error, and I would get the traceback for that specific http request error directly on the browser.

**Comment by dataflake** [comment]
In that case you should take a look at https://zope.readthedocs.io/en/4.x/wsgi.html#debugging-zope-applications-under-wsgi

**Comment by jfoclpf** [comment]
Thanks a lot @dataflake 
so I just need to start zope with

```
bin/runwsgi -e etc/zope.ini
```

sorry to bother, because I was not the onw who made the zope backend installation, I just develop the python with an admin account.

Could you kindly tell me which exact commands I have to run to stop and restart zope with `bin/runwsgi`? Thanks a lot

**Comment by dataflake** [comment]
As the documentation says how you stop and start it depends on how that Zope deployment was installed. The `bin/runwsgi` script is generated by default when the built-in Zope scripts to create a Zope server instance are used. Most people use the buildout recipe `plone.recipe.zope2instance`, which creates its own scripts to stop and start the Zope instance. I don't know how your installation was done so I cannot give you a definitive answer. (This is way beyond the scope of this issue tracker now)

**Comment by jfoclpf** [comment]
Thanks a lot, I guess we can close the issue now.
